<script setup>
useHead({
  title: "Careers at GuildPay - Join Our Team",
  meta: [{ name: "description", content: "Explore open roles at GuildPay. Join a fast-growing fintech team building the future of banking on WhatsApp." }],
})
</script>

<template>
<div>
<div><div></div><div class=""><SiteHeader /><main class="flex flex-col justify-center items-center mt-20 pb-16 md:pb-24"><span class="bg-[#C2D6FF] text-[#162664] text-xs md:text-sm py-3 px-2.5 md:px-3 rounded-full text-center max-w-[405px] md:max-w-full md:py-2"> 🚀 We&#39;re growing, Come build with us </span><h1 class="text-4xl lg:text-[64px] leading-[110.00000000000001%] font-[400] font-switzer tracking-[-1%] text-secondary text-center mt-6"> Join the <br><span class="text-[#0347F5]">GuildPay Team</span></h1><p class="text-[#525866] font-[400] font-switzer text-sm md:text-base mt-3 md:mt-6 w-[90%] md:w-[45%] mx-auto text-center"> We&#39;re on a mission to make banking effortless. If you thrive in fast-paced environments and love building things that matter, we&#39;d love to hear from you. </p></main><section class="bg-[#F6F8FA] py-16 md:py-24" data-v-1d911174><div class="w-contain mx-auto" data-v-1d911174><h2 class="text-2xl md:text-3xl font-switzer font-[700] text-secondary mb-8" data-v-1d911174>Open Roles</h2><div class="flex flex-col lg:flex-row gap-6 relative" data-v-1d911174><div class="w-full lg:w-full shrink-0 transition-[width] duration-500 ease-in-out overflow-hidden" data-v-1d911174><div class="grid-cols-1 grid gap-4 transition-[grid-template-columns] duration-500 ease-in-out" data-lenis-prevent="" data-v-1d911174><div class="border-[#E2E4E9] hover:border-[#0347F5]/40 bg-white rounded-xl p-4 md:p-5 border cursor-pointer transition-all duration-300" data-v-1d911174><div class="flex items-start justify-between gap-3" data-v-1d911174><div class="min-w-0" data-v-1d911174><h3 class="text-base md:text-lg font-switzer font-[600] text-secondary truncate" data-v-1d911174>Motion Designer</h3><p class="text-[#525866] font-switzer text-xs mt-1" data-v-1d911174>Creative</p></div><span class="bg-[#ECFDF3] text-[#027A48] text-xs font-switzer py-1 px-2.5 rounded-full whitespace-nowrap shrink-0" data-v-1d911174>Full-time</span></div><p class="text-[#525866] font-switzer text-sm mt-2 line-clamp-2" data-v-1d911174>This is a craft-forward role. We need someone who can think visually, execute with speed, and ship work that moves people.</p><div class="flex items-center gap-3 mt-3 text-[#525866] font-switzer text-xs" data-v-1d911174><span data-v-1d911174>Mostly Remote / Hybrid</span><span class="w-1 h-1 rounded-full bg-[#D0D5DD]" data-v-1d911174></span><span data-v-1d911174>2+ years</span></div></div></div></div><div class="w-0 opacity-0 lg:absolute lg:right-0 transition-[width,opacity] duration-500 ease-in-out overflow-hidden" data-v-1d911174></div></div></div></section><SiteFooter /></div></div>
</div>
</template>
